export enum INPUTSTATE {
  NORMAL = 'NORMAL',
  VALUED = 'VALUED',
  EDITED = 'EDITED',
  INVALID = 'INVALID',
}

export enum SIZESTYLE {
  BIG = 'BIG',
  MIDDLE = 'MIDDLE',
  SMALL = 'SMALL',
}

export enum COLORSTYLE {
  DOGWOOD_ROSE = 'DOGWOOD_ROSE',
  DARK_MAGENTA = 'DARK_MAGENTA',
}
